site_name: Azure Mobile Apps
site_url: https://azure.github.io/azure-mobile-apps/
repo_url: https://github.com/azure/azure-mobile-apps
edit_uri: blob/master/docs/
copyright: Copyright &copy; Microsoft, Inc.  All Rights Reserved.
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/azure/azure-mobile-apps
theme:
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
  name: material
  palette:
    scheme: preference
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - markdown_include.include:
      base_path: docs
plugins:
  - search
nav:
  - Home: index.md
  - Quickstarts:
    - Android: 
      - Introduction: quickstarts/android/index.md
      - Add Offline Sync: quickstarts/android/offline.md
      - Add Authentication: quickstarts/android/auth.md
      - Add Push Notifications: quickstarts/android/push.md
    - Apache Cordova: 
      - Introduction: quickstarts/cordova/index.md
      - Add Offline Sync: quickstarts/cordova/offline.md
      - Add Authentication: quickstarts/cordova/auth.md
      - Add Push Notifications: quickstarts/cordova/push.md
    - iOS: 
      - Introduction: quickstarts/ios/index.md
      - Add Offline Sync: quickstarts/ios/offline.md
      - Add Authentication: quickstarts/ios/auth.md
      - Add Push Notifications: quickstarts/ios/push.md
    - Windows (UWP): 
      - Introduction: quickstarts/uwp/index.md
      - Add Offline Sync: quickstarts/uwp/offline.md
      - Add Authentication: quickstarts/uwp/auth.md
      - Add Push Notifications: quickstarts/uwp/push.md
    - Xamarin.Android: 
      - Introduction: quickstarts/xamarin-android/index.md
      - Add Offline Sync: quickstarts/xamarin-android/offline.md
      - Add Authentication: quickstarts/xamarin-android/auth.md
      - Add Push Notifications: quickstarts/xamarin-android/push.md
    - Xamarin.Forms: 
      - Introduction: quickstarts/xamarin-forms/index.md
      - Add Offline Sync: quickstarts/xamarin-forms/offline.md
      - Add Authentication: quickstarts/xamarin-forms/auth.md
      - Add Push Notifications: quickstarts/xamarin-forms/push.md
    - Xamarin.iOS: 
      - Introduction: quickstarts/xamarin-ios/index.md
      - Add Offline Sync: quickstarts/xamarin-ios/offline.md
      - Add Authentication: quickstarts/xamarin-ios/auth.md
      - Add Push Notifications: quickstarts/xamarin-ios/push.md
  - How to:
    - Authentication: howto/auth.md
    - Offline Data Sync: howto/datasync.md
    - Work with the Client SDK:
      - Android: howto/client/android.md
      - Apache Cordova: howto/client/cordova.md
      - iOS: howto/client/ios.md
      - Windows (UWP): howto/client/uwp.md
      - Xamarin.Android: howto/client/xamarin-android.md
      - Xamarin.Forms: howto/client/xamarin-forms.md
      - Xamarin.iOS: howto/client/xamarin-ios.md
    - Work with the Server SDK:
      - ASP.NET Framework: howto/server/dotnet-framework.md
      - Node.js: howto/server/nodejs.md
