//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.Mobile.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.Mobile.Server.Properties.RResources", typeof(RResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than {0}..
        /// </summary>
        internal static string ArgumentOutOfRange_GreaterThan {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be less than {0}..
        /// </summary>
        internal static string ArgumentOutOfRange_LessThan {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create or update installation with id &apos;{0}&apos;. Error received: &apos;{1}&apos;..
        /// </summary>
        internal static string NotificationHub_CreateOrUpdateInstallationFailed {
            get {
                return ResourceManager.GetString("NotificationHub_CreateOrUpdateInstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete installation with id &apos;{0}&apos;. Error received: &apos;{1}&apos;..
        /// </summary>
        internal static string NotificationHub_DeleteInstallationFailed {
            get {
                return ResourceManager.GetString("NotificationHub_DeleteInstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NotificationTemplate.Headers property must be null if registration is targeting {0}..
        /// </summary>
        internal static string NotificationHub_DoesNotSupportTemplateHeaders {
            get {
                return ResourceManager.GetString("NotificationHub_DoesNotSupportTemplateHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the SecondaryTile field with header name &apos;{0}&apos;, the header value was null or empty..
        /// </summary>
        internal static string NotificationHub_EmptyHeaderValueInSecondaryTileForHeaderName {
            get {
                return ResourceManager.GetString("NotificationHub_EmptyHeaderValueInSecondaryTileForHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PushChannel field was null or empty in the secondary tile..
        /// </summary>
        internal static string NotificationHub_EmptyPushChannelInSecondaryTile {
            get {
                return ResourceManager.GetString("NotificationHub_EmptyPushChannelInSecondaryTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The InstallationId in the request body does not match the InstallationId in the URL..
        /// </summary>
        internal static string NotificationHub_InstallationIdDoesntMatchUri {
            get {
                return ResourceManager.GetString("NotificationHub_InstallationIdDoesntMatchUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Installation Id was not specified in the URL..
        /// </summary>
        internal static string NotificationHub_InstallationIdNotSpecifiedInUrl {
            get {
                return ResourceManager.GetString("NotificationHub_InstallationIdNotSpecifiedInUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The InstallationId is not a valid Guid..
        /// </summary>
        internal static string NotificationHub_InstallationIdNotValidGuid {
            get {
                return ResourceManager.GetString("NotificationHub_InstallationIdNotValidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required parameter &apos;{0}&apos; was null or empty in the request body..
        /// </summary>
        internal static string NotificationHub_MissingPropertyInRequestBody {
            get {
                return ResourceManager.GetString("NotificationHub_MissingPropertyInRequestBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a connection string named &apos;{0}&apos;. Please ensure that this connection string is present as a service setting..
        /// </summary>
        internal static string NotificationHub_NoConnectionString {
            get {
                return ResourceManager.GetString("NotificationHub_NoConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a service setting named &apos;{0}&apos;. Please ensure that a setting is present..
        /// </summary>
        internal static string NotificationHub_NoHubName {
            get {
                return ResourceManager.GetString("NotificationHub_NoHubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NotificationInstallation was null. This happens when the request body contains malformed JSON..
        /// </summary>
        internal static string NotificationHub_NotificationInstallationWasNull {
            get {
                return ResourceManager.GetString("NotificationHub_NotificationInstallationWasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Templates property of SecondaryTile was null or had no templates specified..
        /// </summary>
        internal static string NotificationHub_SecondaryTileTemplatesWasNullOrEmpty {
            get {
                return ResourceManager.GetString("NotificationHub_SecondaryTileTemplatesWasNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A secondary tile was null in the NotificationInstallation..
        /// </summary>
        internal static string NotificationHub_SecondaryTileWasNull {
            get {
                return ResourceManager.GetString("NotificationHub_SecondaryTileWasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a null Template value in the NotificationInstallation..
        /// </summary>
        internal static string NotificationHub_TemplateWasNull {
            get {
                return ResourceManager.GetString("NotificationHub_TemplateWasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property must be set before the &apos;{1}&apos; property has been accessed..
        /// </summary>
        internal static string NotificationHub_TestSend {
            get {
                return ResourceManager.GetString("NotificationHub_TestSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; class is not a supported notification payload. Supported payloads are: {1}..
        /// </summary>
        internal static string NotificationHub_UnknownPayload {
            get {
                return ResourceManager.GetString("NotificationHub_UnknownPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported service type &apos;{0}&apos; specified in Platform field..
        /// </summary>
        internal static string NotificationHub_UnsupportedPlatform {
            get {
                return ResourceManager.GetString("NotificationHub_UnsupportedPlatform", resourceCulture);
            }
        }
    }
}
