language: objective-c
osx_image:  xcode8.3

env:
  global:
    - PROJECT="sdk/MicrosoftAzureMobile.xcodeproj"
    - CONFIGURATION="DEBUG"

  matrix:
    - SCHEME="MicrosoftAzureMobile"           DESTINATION="OS=10.3.1,name=iPhone 6s"    RUN_TESTS="YES"   SDK="iphonesimulator"
    - SCHEME="MicrosoftAzureMobileFramework"  DESTINATION="OS=10.3.1,name=iPhone 6s"    RUN_TESTS="YES"   SDK="iphonesimulator"

before_install:
  - xcrun simctl list
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - brew install carthage

script:
  - open -b com.apple.iphonesimulator
  - set -o pipefail
  - COMMAND="env NSUnbufferedIO=YES xcodebuild -project '$PROJECT' -scheme '$SCHEME' -sdk '$SDK' -configuration '$CONFIGURATION'"

  # Add xcpretty
  - COMMAND_SUFFIX=" | tee xcodebuild.log | xcpretty -f `xcpretty-travis-formatter`"
  
  # Run tests
  - if [ $RUN_TESTS == "YES" ]; then
      COMMAND+=" -destination '$DESTINATION' XCODEBUILD_GCC_PREPROCESSOR_DEFINITIONS=\"CI=1\" "
      COMMAND="$COMMAND clean build-for-testing $COMMAND_SUFFIX && travis_retry $COMMAND test-without-building $COMMAND_SUFFIX";
    else
      COMMAND+="$COMMAND_SUFFIX";
    fi

  - echo $COMMAND
  - eval $COMMAND && rm xcodebuild.log

# Use better failure diagnostics, copied from https://github.com/0xced/XCDYouTubeKit
after_failure:
  - cat xcodebuild.log
  - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
  - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
  - sleep 5