# Uncomment the next line to define a global platform for your project
platform :ios, '121212121212121212121212.0'

target 'ZumoQuickstart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZumoQuickstart

end
